### ISSUE TITLE
.env to pass IP address

### ISSUE THREAD

**Issue by giuliafrascaria** [UCY-LINC-LAB/fogify#2]
Hi! 
I am trying to deploy fogify to run an experiment, and I'm trying to run that through the docker compose rather than baremetal. 

However even though I set the variables in a .env file and pass that to the containers, the IP of the host is not used to run the agent and controller

Is that an expected behavior or does that mean I missed some setting for the deployment? 
Thank you!

`Namespace(agent=True, agent_ip='192.168.1.102', controller=False)`
`Running on http://0.0.0.0:5500/ (Press CTRL+C to quit)`

**Comment by MosesSymeonidis** [comment]
Hi,
Thanks for trying Fogify and for your time.

If I understand correctly, your problem is that the logs refer only the `0.0.0.0` as IP. If this is the case, yes that is expected behavior. Fogify needs the IP of your machine to communicate with the Docker Swarm master and make requests to the monitoring agent. The `0.0.0.0` logged due to the flask server running for both controller & agent, but, anyway, they expose their ports (5000 &5500 respectively) to your machine through the docker-compose port binding.
Did you try to perform any experiment/example on Fogify and it failed?
If you faced any issue with that, please provide more information about it.

Thank you

**Comment by giuliafrascaria** [comment]
Thanks for your help, yes I managed to run the app now!
